apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
      - api.bistrobytes.com.sg
      secretName: bistrobytes-tls
    - hosts:
      - integration.bistrobytes.com.sg
      secretName: bistrobytes-tls
    - hosts:
      - cms.bistrobytes.com.sg
      secretName: bistrobytes-tls
    - hosts:
      - admin.bistrobytes.com.sg
      secretName: bistrobytes-tls
  rules:
  - host: cms.bistrobytes.com.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks-helloworld
            port:
              number: 80
  - host: admin.bistrobytes.com.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks-helloworld
            port:
              number: 80
  - host: api.bistrobytes.com.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks-helloworld
            port:
              number: 80
  - host: integration.bistrobytes.com.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-demo
            port:
              number: 80
